import type { Metadata } from "next";
import { Dosis, Manrope } from "next/font/google";
import "./globals.css";
import ShaderBackground from "@/components/shader-background";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const dosis = Dosis({
  variable: "--font-dosis",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${manrope.variable} ${dosis.variable} antialiased dark h-full flex flex-col`}
        suppressHydrationWarning={true}
      >
        <Navbar/>
        <div className="flex-1 relative">
          <ShaderBackground/>
          <div className="relative z-10">
            {children}
          </div>
        </div>
        <Footer/>
        
      </body>
    </html>
  );
}
