import type { Metadata } from "next";
import { Dosis, Manrope } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import ShaderBackground from "@/components/shader-background";


const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const dosis = Dosis({
  variable: "--font-dosis",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.variable} ${dosis.variable} antialiased dark`}
        suppressHydrationWarning={true}
      >
        <Navbar />
        <div className="">
          <ShaderBackground/>
          {children}
        </div>
      </body>
    </html>
  );
}
